# Generated by Django 5.2.17 on 2026-09-05 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_complaints', models.PositiveIntegerField(default=0)),
                ('resolved_complaints', models.PositiveIntegerField(default=0)),
                ('active_complaints', models.PositiveIntegerField(default=0)),
                ('max_daily_capacity', models.PositiveSmallIntegerField(default=20, help_text='Maximum new complaints this official can receive per day')),
                ('is_available', models.BooleanField(default=True)),
                ('unavailable_until', models.DateTimeField(blank=True, null=True)),
                ('last_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('official', models.OneToOneField(limit_choices_to={'role__in': ['OFFICIAL', 'MINISTER']}, on_delete=django.db.models.deletion.CASCADE, related_name='workload', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Official Workload',
                'verbose_name_plural': 'Official Workloads',
                'ordering': ['active_complaints'],
            },
        ),
        migrations.CreateModel(
            name='RoutingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_method', models.CharField(choices=[('AUTO', 'Automatic (AI)'), ('MANUAL', 'Manual'), ('ESCALATION', 'Escalation'), ('TRANSFER', 'Transfer')], default='AUTO', max_length=20)),
                ('routing_reason', models.TextField(blank=True)),
                ('routing_confidence', models.FloatField(default=0.0, help_text='Confidence score of the AI routing decision (0-100%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_logs', to='complaints.complaint')),
                ('new_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routings_to', to='users.department')),
                ('new_official', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routings_to', to=settings.AUTH_USER_MODEL)),
                ('previous_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routings_from', to='users.department')),
                ('previous_official', models.ForeignKey(blank=True, help_text='Official before this routing (None for first assignment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routings_from', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Routing Log',
                'verbose_name_plural': 'Routing Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='routing_rou_created_a9a208_idx'), models.Index(fields=['complaint'], name='routing_rou_complai_355b74_idx')],
            },
        ),
    ]
