# Generated by Django 5.2.17 on 2026-09-05 08:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTaskChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('work_type', models.CharField(blank=True, choices=[('INSPECTION', 'Inspection'), ('REPAIR', 'Repair'), ('CLEANING', 'Cleaning'), ('INSTALLATION', 'Installation'), ('REMOVAL', 'Removal'), ('MAINTENANCE', 'Maintenance'), ('SURVEY', 'Survey'), ('OTHER', 'Other')], max_length=100)),
                ('items', models.JSONField(blank=True, default=list, help_text='List of checklist items with name, description, and is_required')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Field Task Checklist Template',
                'verbose_name_plural': 'Field Task Checklist Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FieldTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(editable=False, help_text='Unique task ID (e.g., FT-987654)', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ON_SITE', 'On Site'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location_address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('work_type', models.CharField(blank=True, choices=[('INSPECTION', 'Inspection'), ('REPAIR', 'Repair'), ('CLEANING', 'Cleaning'), ('INSTALLATION', 'Installation'), ('REMOVAL', 'Removal'), ('MAINTENANCE', 'Maintenance'), ('SURVEY', 'Survey'), ('OTHER', 'Other')], max_length=100)),
                ('materials_used', models.TextField(blank=True)),
                ('labor_hours', models.FloatField(blank=True, null=True)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('before_photo', models.ImageField(blank=True, null=True, upload_to='fieldwork/before/')),
                ('after_photo', models.ImageField(blank=True, null=True, upload_to='fieldwork/after/')),
                ('completion_notes', models.TextField(blank=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('quality_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('quality_feedback', models.TextField(blank=True)),
                ('gps_track', models.JSONField(blank=True, default=list, help_text='List of GPS coordinates with timestamps')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'FIELD_WORKER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_tasks', to='complaints.complaint')),
                ('jurisdiction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_tasks', to='users.jurisdiction')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Field Task',
                'verbose_name_plural': 'Field Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldTaskChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_checklist_items', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='fieldwork.fieldtask')),
            ],
            options={
                'verbose_name': 'Field Task Checklist',
                'verbose_name_plural': 'Field Task Checklists',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FieldTaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ON_SITE', 'On Site'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ON_SITE', 'On Site'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_status_changes', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='fieldwork.fieldtask')),
            ],
            options={
                'verbose_name': 'Field Task History',
                'verbose_name_plural': 'Field Task Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldWorkerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('accuracy', models.FloatField(help_text='Accuracy in meters')),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('battery_level', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_updates', to='fieldwork.fieldtask')),
                ('worker', models.ForeignKey(limit_choices_to={'role': 'FIELD_WORKER'}, on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Field Worker Location',
                'verbose_name_plural': 'Field Worker Locations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldWorkerPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('rejected_tasks', models.PositiveIntegerField(default=0)),
                ('avg_completion_time', models.DurationField(blank=True, null=True)),
                ('total_working_hours', models.FloatField(default=0.0)),
                ('avg_quality_rating', models.FloatField(default=0.0)),
                ('quality_rating_count', models.PositiveIntegerField(default=0)),
                ('total_distance_traveled', models.FloatField(default=0.0, help_text='Distance in kilometers')),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('performance_score', models.FloatField(default=0.0, help_text='0-100%')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.OneToOneField(limit_choices_to={'role': 'FIELD_WORKER'}, on_delete=django.db.models.deletion.CASCADE, related_name='field_performance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Field Worker Performance',
                'verbose_name_plural': 'Field Worker Performances',
                'ordering': ['-performance_score'],
            },
        ),
        migrations.AddIndex(
            model_name='fieldtask',
            index=models.Index(fields=['-created_at'], name='fieldwork_f_created_311c40_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldtask',
            index=models.Index(fields=['status'], name='fieldwork_f_status_cc3575_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldtask',
            index=models.Index(fields=['assigned_to'], name='fieldwork_f_assigne_5a1e05_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldtask',
            index=models.Index(fields=['complaint'], name='fieldwork_f_complai_686bff_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldworkerlocation',
            index=models.Index(fields=['-created_at'], name='fieldwork_f_created_096b67_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldworkerlocation',
            index=models.Index(fields=['worker'], name='fieldwork_f_worker__c77075_idx'),
        ),
    ]
