# Generated by Django 5.2.17 on 2026-09-05 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_verification_passed', models.BooleanField(default=False)),
                ('ai_confidence_score', models.FloatField(default=0.0, help_text='Average AI confidence score across proofs (0-100%)')),
                ('ai_verified_at', models.DateTimeField(blank=True, null=True)),
                ('ai_notes', models.TextField(blank=True)),
                ('human_verification_passed', models.BooleanField(default=False)),
                ('human_verification_notes', models.TextField(blank=True)),
                ('human_verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_fully_verified', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_result', to='complaints.complaint')),
                ('human_reviewer', models.ForeignKey(blank=True, limit_choices_to={'role': 'REVIEWER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_results_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Result',
                'verbose_name_plural': 'Verification Results',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('AI_VERIFICATION', 'AI Verification'), ('HUMAN_VERIFICATION', 'Human Verification'), ('REJECTION', 'Rejection'), ('RESET', 'Reset')], max_length=50)),
                ('is_ai_action', models.BooleanField(default=False)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_actions', to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='verification.verificationresult')),
            ],
            options={
                'verbose_name': 'Verification Audit Log',
                'verbose_name_plural': 'Verification Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
