# Generated by Django 5.2.17 on 2026-09-05 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(unique=True)),
                ('total_complaints', models.PositiveIntegerField(default=0)),
                ('new_complaints', models.PositiveIntegerField(default=0)),
                ('resolved_complaints', models.PositiveIntegerField(default=0)),
                ('escalated_complaints', models.PositiveIntegerField(default=0)),
                ('avg_resolution_days', models.FloatField(default=0.0)),
                ('avg_citizen_rating', models.FloatField(default=0.0)),
                ('sla_compliance_rate', models.FloatField(default=0.0)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Analytics Snapshot',
                'verbose_name_plural': 'Analytics Snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='IssuePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='List of keywords that identify this pattern')),
                ('complaint_count', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('avg_priority_score', models.FloatField(default=0.0)),
                ('max_priority_score', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Issue Pattern',
                'verbose_name_plural': 'Issue Patterns',
                'ordering': ['-complaint_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OfficialPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_complaints', models.PositiveIntegerField(default=0)),
                ('resolved_complaints', models.PositiveIntegerField(default=0)),
                ('rejected_complaints', models.PositiveIntegerField(default=0)),
                ('pending_complaints', models.PositiveIntegerField(default=0)),
                ('overdue_complaints', models.PositiveIntegerField(default=0)),
                ('avg_response_time', models.DurationField(blank=True, null=True)),
                ('avg_resolution_time', models.DurationField(blank=True, null=True)),
                ('avg_citizen_rating', models.FloatField(default=0.0)),
                ('avg_priority_score', models.FloatField(default=0.0)),
                ('sla_compliance_rate', models.FloatField(default=0.0)),
                ('sla_breach_count', models.PositiveIntegerField(default=0)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('messages_received', models.PositiveIntegerField(default=0)),
                ('avg_message_response_time', models.DurationField(blank=True, null=True)),
                ('performance_score', models.FloatField(default=0.0, help_text='0-100%')),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Official Performance',
                'verbose_name_plural': 'Official Performances',
                'ordering': ['-performance_score'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_complaints', models.PositiveIntegerField(default=0)),
                ('resolved_complaints', models.PositiveIntegerField(default=0)),
                ('rejected_complaints', models.PositiveIntegerField(default=0)),
                ('pending_complaints', models.PositiveIntegerField(default=0)),
                ('avg_resolution_time', models.DurationField(blank=True, null=True)),
                ('median_resolution_time', models.DurationField(blank=True, null=True)),
                ('avg_citizen_rating', models.FloatField(default=0.0)),
                ('avg_priority_score', models.FloatField(default=0.0)),
                ('sla_compliance_rate', models.FloatField(default=0.0)),
                ('sla_breach_count', models.PositiveIntegerField(default=0)),
                ('performance_score', models.FloatField(default=0.0, help_text='0-100%')),
                ('rank', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_performance', to='users.department')),
            ],
            options={
                'verbose_name': 'Department Performance',
                'verbose_name_plural': 'Department Performances',
                'ordering': ['-performance_score'],
            },
        ),
        migrations.CreateModel(
            name='HeatmapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('complaint_count', models.PositiveIntegerField(default=0)),
                ('resolved_count', models.PositiveIntegerField(default=0)),
                ('pending_count', models.PositiveIntegerField(default=0)),
                ('low_priority', models.PositiveIntegerField(default=0)),
                ('medium_priority', models.PositiveIntegerField(default=0)),
                ('high_priority', models.PositiveIntegerField(default=0)),
                ('critical_priority', models.PositiveIntegerField(default=0)),
                ('category_data', models.JSONField(blank=True, default=dict, help_text='Dictionary of category IDs to counts')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Heatmap Data',
                'verbose_name_plural': 'Heatmap Data',
                'ordering': ['-complaint_count'],
                'unique_together': {('latitude', 'longitude', 'start_date', 'end_date')},
            },
        ),
    ]
