# Generated by Django 5.2.17 on 2026-09-05 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('complaints', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issuepattern',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_issue_patterns', to='complaints.complaintcategory'),
        ),
        migrations.AddField(
            model_name='issuepattern',
            name='jurisdictions',
            field=models.ManyToManyField(blank=True, related_name='analytics_issue_patterns', to='users.jurisdiction'),
        ),
        migrations.AddField(
            model_name='issuepattern',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_analytics_patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='officialperformance',
            name='official',
            field=models.OneToOneField(limit_choices_to={'role__in': ['OFFICIAL', 'MINISTER']}, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_performance', to=settings.AUTH_USER_MODEL),
        ),
    ]
