# Generated by Django 5.2.17 on 2026-09-05 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_services', '0001_initial'),
        ('complaints', '0001_initial'),
        ('messaging', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiservicelog',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_service_logs', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='aiservicelog',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_logs', to='ai_services.aimodel'),
        ),
        migrations.AddField(
            model_name='aiservicelog',
            name='proof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_service_logs', to='complaints.complaintproof'),
        ),
        migrations.AddField(
            model_name='aiservicelog',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_ai_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aitrainingdata',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_training_data', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imageanalysisresult',
            name='proof',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_analysis_result', to='complaints.complaintproof'),
        ),
        migrations.AddField(
            model_name='priorityscoringresult',
            name='complaint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='priority_scoring_result', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='routingsuggestion',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_routing_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routingsuggestion',
            name='complaint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routing_suggestion', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='routingsuggestion',
            name='suggested_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_suggestions', to='users.department'),
        ),
        migrations.AddField(
            model_name='routingsuggestion',
            name='suggested_jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_suggestions', to='users.jurisdiction'),
        ),
        migrations.AddField(
            model_name='routingsuggestion',
            name='suggested_officials',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['OFFICIAL', 'MINISTER']}, related_name='routing_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textanalysisresult',
            name='complaint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_analysis_result', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='translationrequest',
            name='complaint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_requests', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='translationrequest',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_requests', to='messaging.message'),
        ),
        migrations.AddIndex(
            model_name='aiservicelog',
            index=models.Index(fields=['-created_at'], name='ai_services_created_3322de_idx'),
        ),
        migrations.AddIndex(
            model_name='aiservicelog',
            index=models.Index(fields=['service_name'], name='ai_services_service_81e889_idx'),
        ),
        migrations.AddIndex(
            model_name='aiservicelog',
            index=models.Index(fields=['status'], name='ai_services_status_496adc_idx'),
        ),
    ]
